README.md

I think you meant `HasCallStack` rather than `HasCallback`.

Change `HasCallback` to `HasCallStack` in the docs

---

README.md
src/RIO/Logger.hs

No -XImplicitParams

---

README.md

Note on unqualified infix operators

---

src/RIO/Prelude/Reexports.hs

Not actually searching for these, I just keep reaching for the one thing that fell of the shelf!

Reexport Data.Monoid.Alt from Prelude

---

rio/src/RIO/Prelude/Display.hs
rio/src/RIO/Prelude/Logger.hs
rio/src/RIO/Process.hs

Also renames helper functions and adds a bunch of missing instances. CC
@chrisdone.

Better display type class 

---

.travis.yml
rio/src/RIO/Prelude/Reexports.hs
stack.yaml

Fixes #33 (I think). Pinging @tejon.

Switch to Semigroup's <>

---

rio/ChangeLog.md
rio/package.yaml
rio/src/RIO/Prelude/Logger.hs
rio/test/RIO/LoggerSpec.hs

Opening this PR in favor of #93

Allow reload for logMinLevel and logVerboseFormat settings

---

rio/src/RIO/Prelude/Reexports.hs

Reexport Numeric.Natural.Natural

---

rio/ChangeLog.md
rio/src/RIO/Prelude/Reexports.hs

Provide (<&>); reexport from base >= 4.11, defined locally otherwise

---

rio/ChangeLog.md
rio/src/RIO/Prelude/Reexports.hs

Re-export `Data.Proxy.Proxy(..)` given is a common type to import in projects

Re-export Data.Proxy.Proxy

---

rio/ChangeLog.md
rio/package.yaml
rio/src/RIO/Prelude/Display.hs

Fix for #144 
Also includes version bump and changelog update.

Addition of `textDisplay`.

---

rio/README.md

Adds additional warnings to the documentation, as discussed in #135. @maxgabriel are you okay with the attribution?

Adds more warnings

---

rio/ChangeLog.md
rio/src/RIO/Prelude/Reexports.hs

Export Seq from RIO.Prelude.Reexports

---

etc/template/README.md

Just to give a sense of what's the expected outcome.

Add execute comments to the README

---

rio/ChangeLog.md
rio/src/RIO/NonEmpty.hs
rio/src/RIO/NonEmpty/Partial.hs

RIO.NonEmpty, RIO.NonEmpty.Partial

---

rio/src/RIO/Text.hs

Fixed typo in module documentation for RIO.Text

---

rio/ChangeLog.md
rio/src/RIO/Prelude/Logger.hs
rio/test/RIO/LoggerSpec.hs

Adds logFormat to LogOptions

---

rio/src/RIO/Prelude/Logger.hs

Mention UTF-8 nuances in logOptionsHandle documentation.

---

rio/src/RIO/Prelude/Logger.hs

...we will enabled -> we will enable

Fix small typo

---

rio/src/RIO/Process.hs

Existing `RIO.Process.augmentPathMap` is specialised to the PATH environment variable. There are other environment variables commonly used to contain lists of paths (eg PKG_CONFIG_PATH) and it would be helpful to be able to augment them in the same way. This pull request proposes to extend the API by providing the generalised:
~~~haskell
augmentPathMap' :: Text -> [FilePath] -> EnvVars -> Either ProcessException EnvVars
~~~
Existing `augmentPathMap` then is defined as `augmentPathMap = augmentPathMap' "PATH"`.
`augmentPath` is not specialised to PATH or any other environment variable. This pull request improves its Haddock documentation to clarify that (1) it augments the value of any environment variable assumed to list paths, and (2) it does not check that the existing value lists …

Export a generalised version of `augmentPathMap` (as `augmentPathMap'`)

---

rio/README.md

README.md: Fix image URL

---

rio/src/RIO/Deque.hs
rio/src/RIO/Prelude/Display.hs
rio/src/RIO/Prelude/Extra.hs
rio/src/RIO/Prelude/Logger.hs
rio/src/RIO/Prelude/RIO.hs
rio/src/RIO/Process.hs
rio/test/RIO/DequeSpec.hs
rio/test/RIO/FileSpec.hs
rio/test/RIO/ListSpec.hs
rio/test/RIO/LoggerSpec.hs
rio/test/RIO/Prelude/RIOSpec.hs
rio/test/RIO/Prelude/SimpleSpec.hs

This pull request accepts the HLint v3.10 suggestions. None of them seemed to be controversial. A few are stylistic but not offensive and adopting HLint's style is a path of least resistance.

Accept HLint v3.10 hints for rio package
