src/RIO.hs
src/RIO/ByteString/Lazy.hs
src/RIO/Directory.hs
src/RIO/FilePath.hs
src/RIO/HashMap.hs
src/RIO/HashSet.hs
src/RIO/List.hs
src/RIO/Map.hs
src/RIO/Prelude.hs
src/RIO/Set.hs
src/RIO/Text.hs
src/RIO/Text/Lazy.hs
src/RIO/Time.hs
src/RIO/Vector.hs
src/RIO/Vector/Boxed.hs
src/RIO/Vector/Storable.hs
src/RIO/Vector/Unboxed.hs

Rewrite export list for RIO.Prelude such that all reexports other than those from UnliftIO are rendered on the RIO haddock page.  As UnliftIO is such a huge import I left that as a module link pending what you want to do with it.
Rewrite export lists in all other modules that only reexport definitions such that their haddocks have links to the source modules.  This probably should be improved later but in my opinion will do for now as a quick fix.
Addresses issue #17

Improve haddock generation (see #17)

---

src/RIO/ByteString/Lazy.hs
src/RIO/HashMap.hs
src/RIO/HashSet.hs
src/RIO/List.hs
src/RIO/Map.hs
src/RIO/Set.hs
src/RIO/Text.hs
src/RIO/Text/Lazy.hs
src/RIO/Vector.hs
src/RIO/Vector/Boxed.hs
src/RIO/Vector/Storable.hs
src/RIO/Vector/Unboxed.hs

Addressing #35.
For now, I went with a sort of middle ground with regards to current discussion in #12: the first layer of modules (`RIO.*`) have single-letter abbreviations, but their children are unabbreviated, e.g.:
```
import qualified RIO.Vector.Unboxed as V.Unboxed
```
The exception to this is `RIO.HashMap` and `RIO.HashSet`, which are `M.Hash` and `S.Hash` respectively, reflecting a vague hunch that it wouldn't hurt to move them in the hierarchy accordingly.

Pervasive qualified import name documentation

---

src/RIO/Prelude/Reexports.hs

Noticed this was missing. There may be a principled reason for that, if so disregard.

Reexport Data.Bool.bool

---

src/RIO/Map/Unchecked.hs

Looks like these got missed. I put them in `Unchecked` because the matching `from*` are unchecked, and (I believe?) `toAscList . fromAscList = id` so you can technically get an unsorted list out of it. Arguably this is covered by `from*` being in `Unchecked`, in which case  these can move to `RIO.Map` proper; I'm on the fence about it.

Reexport toAscList, toDescList from RIO.Map.Unchecked

---

README.md

Currently, the README does not show up on https://github.com/commercialhaskell/rio .  This adds a symlink to the README.  This way it can still be directly included in the rio package.  This will degrade decently on filesystems that do not support symbolic links, it will just be a text file with the path to the readme you should look at.

Add a symbolic link to README.md so that it shows up on github

---

rio/src/RIO/Prelude/Reexports.hs

I think it is useful to have some more exports from `UnliftIO.Concurrent`. 
Another option would be to re-export `UnliftIO.Concurrent` as `RIO.Concurrent`, let me know your thoughts

Add more exports from UnliftIO.Concurrent

---

rio/package.yaml

Many of these modules seem a bit out of place, or otherwise only make sense in
the context of being re-exported in Rio. Particularly, the following only make
sense in that context: Extra, IO, Reexports, Renames, Text.
As such, I think for the stable release it makes sense to just hide all of them.
In later releases, additional modules / exports can be added to allow importing
of some of these things individually. This is described in #71

Hide RIO.Prelude.* modules

---

rio/src/RIO/Prelude/IO.hs
rio/test/RIO/Prelude/IOSpec.hs

This allows the handle API to automatically deal with LF vs CRLF line
endings correctly. Pointed out to me _somewhere_ by @sol, I don't
remember where I saw it.

Use textual I/O to handle line endings

---

rio/src/RIO/List.hs
rio/src/RIO/Prelude/Text.hs
rio/src/RIO/Text.hs

The main place this is useful is after use of some 'lines' function that splits
only on \n.  I think for these cases it makes more sense to have new 'lines'
functions which handle both \r\n and \n.

Remove stripCR function

---

rio/src/RIO/Prelude/Reexports.hs

Reasoning:
* Kept 'First' / 'Last' because they are useful in many practical circumstances.
Particularly when used with fields of a datatype + Monoid deriving.
* 'Alt' is a very general name, and off the top of my head I didn't know what it
does.
* 'Product' / 'Sum' are pretty clear, but they are also rather popular type
constructor names, if you search them in hoogle.  A lot of collisions and not
used a whole ton.
* 'All' / 'Any' are also pretty clear, but similarly a fairly popular type name.
* Kept 'Endo' because I like it, though tbh I don't use it much.

Remove some Data.Monoid wrappers

---

etc/.gitignore
etc/make-template.hs
etc/stack.yaml
etc/template/.gitignore
etc/template/ChangeLog.md
etc/template/LICENSE
etc/template/README.md
etc/template/Setup.hs
etc/template/app/Main.hs
etc/template/package.yaml
etc/template/src/Import.hs
etc/template/src/Lib.hs
etc/template/src/Run.hs
etc/template/src/Types.hs
etc/template/src/Util.hs
etc/template/test/Spec.hs
etc/template/test/UtilSpec.hs

This is intended for usage with `stack new`. The code here is certainly up for improvement.

Add a template

---

rio-orphans/ChangeLog.md
rio-orphans/package.yaml
rio-orphans/src/RIO/Orphans.hs

With this PR, we are going to be able to support libraries like persistent, which require `monad-logger` typeclass instances

Add support for monad-logger typeclassess for RIO

---

rio/ChangeLog.md
rio/src/RIO/Prelude/Logger.hs

This pull request adds the function `newLogFunc` to the `RIO.Prelude.Logger` module, this function returns a tuple with a `LogFunc` and a teardown sub-routine. This function is useful when using a mechanism other than `bracket` (e.g. [`componentm`](https://github.com/roman/Haskell-componentm/tree/master/componentm)) to deal with resource management.

Allow alloc of LogFunc outside a with block

---

rio/ChangeLog.md
rio/src/RIO/List.hs
rio/src/RIO/List/Partial.hs

This PR adds safe versions of partial functions on lists. This will close ticket #82

Alternative (safe) functions for RIO.List.Partial

---

rio/ChangeLog.md
rio/package.yaml
rio/src/RIO/Prelude/Reexports.hs

These are useful, simple, ubiquitous, and heavily referenced in the existing reexport docs... and we're already reexporting `Void` so I don't think they're going to shift any threshold of newbie confusion!

Reexport Data.Functor.Const.Const, Data.Functor.Identity.Identity

---

rio/ChangeLog.md
rio/src/RIO/Prelude/Reexports.hs

Not strictly necessary if the reexport of Identity is adopted, but saves a bit of boilerplate.

Reexport Control.Monad.Reader.Reader, runReader

---

rio/ChangeLog.md
rio/src/RIO/Partial.hs
rio/src/RIO/Prelude/Reexports.hs

Hi, I noticed these are missing when I tried to use them.

Export Prelude.fromEnum from RIO, export fromJust, read and toEnum form RIO.Partial

---

rio/ChangeLog.md
rio/src/RIO/Prelude/Logger.hs
rio/test/RIO/LoggerSpec.hs

This change adds the `noLogging` combinator, see diff for rationale.

Add noLogging combinator

---

rio/ChangeLog.md
rio/src/RIO/Prelude/Reexports.hs

Fits in with `(&)` and `(<&>)`.

Re-export Control.Category.>>>

---

rio/src/RIO/Prelude/Logger.hs

The improved documentation explains what are all the side-effects from using a `True` value in the Debug flag

Improve documentation of logOptionsHandle

---

rio/ChangeLog.md
rio/src/RIO/Prelude/Logger.hs

Fixes #131 
Simple change in `logOptionsHandle`. Updated the haddock comment. Updated the change log.

logUseColor now defaults to False on Windows, even when verbose

---

rio/src/RIO/List.hs
rio/test/RIO/ListSpec.hs

Remove unnecessary `Ord` constraint from min/max functions

---

rio/ChangeLog.md
rio/src/RIO/Partial.hs

I think we just overlooked these with #115, they have the same sort of bounds-related partiality as `toEnum` which was included there.

Re-export `pred`, `succ` in `RIO.Partial`.

---

rio/src/RIO/Prelude/Logger.hs

In the [example code](http://hackage.haskell.org/package/rio-0.1.5.0/docs/RIO.html#v:withLogFunc) for `withLogFunc` on haddock, backslash before `lf ->` is not properly rendered.
This PR just fixes it.

Fix backslash to be appeared in haddock

---

rio/ChangeLog.md
rio/src/RIO/Map.hs
rio/src/RIO/Map/Unchecked.hs

I don't think there is anything wrong/unchecked with:
* `Data.Map.Strict.toAscList`
* `Data.Map.Strict.toDescList`
They do not have any preconditions, other than the `Map` itself be valid. In fact `RIO.Set` exports corresponding functions.
I did not remove them from `RIO.Map.Unchecked`, otherwise it would be a breaking change, so it should be done at the next major release instead.

Move incorrectly classified Map conversion functions: `toAscList`, `toDescList`

---

rio/ChangeLog.md
rio/package.yaml
rio/src/RIO.hs
rio/src/RIO/Prelude/Exit.hs
rio/src/RIO/Prelude/Reexports.hs

into the Rio `Prelude`, and re-exported from there.

add lifted versions of `System.Exit.exitFailure` and `exitSuccess`

---

rio/ChangeLog.md
rio/package.yaml
rio/src/RIO/Prelude.hs
rio/src/RIO/Prelude/Types.hs

* Remove reexport of `empty`, which was introduced in `rio-0.1.9.0`
* Bumps up version
* Updates changelog together with a missed change for the previous version

Remove accidental reexport of `Control.Applicative.empty`  

---

rio/ChangeLog.md
rio/src/RIO/Prelude/Display.hs

Because of derived instance with `GeneralizedNewtypeDeriving`, `mconcat` breaks list fusion and causes extra allocations when used with `Utf8Builder`. Here is a way to reproduce: 
```haskell
runSimpleApp $ do
logInfo $ foldr (<>) mempty $ fuseThis ["foo", "bar", "-", "<>"]
logInfo $ foldr mappend mempty $ fuseThis ["foo", "bar", "-", "mappend"]
logInfo $ mconcat $ fuseThis ["foo", "bar", "-", "mconcat"]
```
`fuseThis` comes from [`Data.List.Fusion.Probe`](http://hackage.haskell.org/package/list-fusion-probe-0.1.0.8/docs/Data-List-Fusion-Probe.html)
Code above results in:
```
foobar-<>
foobar-mappend
fuse-builder-exe: fuseThis: List did not fuse
CallStack (from HasCallStack):
error, called at ./Data/List/Fusion/Probe.hs:52:16
```
But with the fix in this PR:
```
foobar-<>
foobar-mappend …
```

Custom `Monoid` instance for `Utf8Builder`

---

rio/ChangeLog.md
rio/src/RIO/Prelude.hs

Addresses #169 
The only reservation I have here is that for some reason there's no record for deconstructing a `Down` (e.g. `getDown`, `unDown`). But there also doesn't seem to be any competing implementation which does provide that.

Re-export Data.Ord.Down from RIO.Prelude

---

rio/ChangeLog.md
rio/src/RIO/Prelude/Types.hs

I've chosen not to export the `(:|)` constructor here due to conflicts in `generic-random` and `opaleye`. Generally the smart de/constructor functions in `RIO.NonEmpty` are better anyway.

Export Data.List.NonEmpty.NonEmpty from RIO.Prelude.Types

---

rio/ChangeLog.md
rio/src/RIO/Prelude/Logger.hs
rio/test/RIO/LoggerSpec.hs

Fixes #178
I’ve also added a test case.

Fix handling of non-ASCII characters in logSticky

---

rio/ChangeLog.md
rio/package.yaml
rio/src/RIO/NonEmpty.hs
rio/src/RIO/Prelude/Types.hs
stack.yaml

This PR builds off of #174 , etc., to:
- actually expose the `RIO.NonEmpty.*` modules
- correct some minor documentation issues
- expose the `(:|)` operator after all
Previous work had purposefully left out `(:|)`, citing conflicts with other packages. However, since `NonEmpty` is from `base` and the cited conflicts are not, I believe that the `NonEmpty` version should be considered the "real" one. Note that the vanilla List type itself and its constructors are always exposed regardless of `NoImplicitPrelude`, and so we could argue that its twin (`NonEmpty`) should be exposed in the same way.
I'm willing to reconsider this stance on `(:|)` of course, and have left its addition as the final commit in this PR, to aid a rollback.

Reworking `NonEmpty`

---

rio/src/RIO.hs
rio/src/RIO/Prelude/Logger.hs
rio/src/RIO/Prelude/RIO.hs

This PR adds generic logging to RIO such that you can log any data type rather than just `Utf8Builder`, and you don't have to decide what log level or format your logs are going to be until later. This is not intended as a replacement for RIO's existing logger, but rather allows different backends to be used, including the "classic" logger. 
Many apps I write might want to log in different ways with non trivial filtering of the logs, with sublogging, and I don't necessarily know right away what levels my logs should be at the call site (it might depend on context). Going through a data type isn't necessarily as fast as going straight to `Utf8Builder`, but that's a conscious trade-off. Idiom is an example of such an app that is using this.
(**Aside**: This PR isn't meant to address various …

Add generic logging

---

rio/ChangeLog.md
rio/package.yaml
rio/src/RIO/Prelude/IO.hs

We have `withLazyFile`/`readFileBinary`/`writeFileBinary`. I think `readFileUtf8` and `writeFileUtf8` are missing a convenient third friend...

Introduce withLazyFileUtf8

---

rio/src/RIO/Process.hs

The `findExecutable name =` limb of `RIO.Process.findExecutable` no longer filters by the `System.Directory.executable` test and, so, takes into account fully the list of executable extensions in the `ProcessContext`.
This also extends the Haddock documentation for `ProcessContext`, `mkProcessContext`, `mkDefaultProcessContext` and `findExecutable`.
On Windows, an excutable with a filename with no extension cannot be executed from the command line. `mkProcessContext` and `findExecutable` are modified accordingly. `mkProcessContext` now excludes `""` from the head of the list of extensions and the limbs of `findExecutable` use a `isWindows && FP.hasExtension` test to decide whether to include the name itself in the list of names tried.
The `isWindows` function is moved from a `where` to be …

Fix #205 On Windows, findExecutable uses ProcessContext consistently

---

rio/ChangeLog.md
rio/src/RIO/Prelude/Simple.hs
rio/src/RIO/Process.hs

@snoyberg I think `lookupEnvVar` would have been a more consistent name, considering that there are functions with names:
* `modifyEnvVars`
* `withModifyEnvVars`
* `envVarsL`
* `envVarsStringsL`. 
All of which operate on `EnvVars` in the `ProcessContext`, but do not mention it in the name. In fact `lookupEnvFromContext` will be the first function to have both `Context` (without `Process`) and `Env` (without `Var`) in its name.
That being said, I really don't care about it, just wanted to express this observation.
As always, let me know if there is anything you'd like me to change./

Addition of `mkSimpleApp` and `lookupEnvFromContext`. Fix #208

---

rio/src/RIO/Prelude/Logger.hs
rio/test/RIO/LoggerSpec.hs

In both default and verbose mode, providing a non-empty source <src> will
qualify a message \<msg\> as "(\<src\>) \<msg\>".
Instead of #215.

Change log functions to print the LogSource argument

---

rio/ChangeLog.md
rio/package.yaml
rio/rio.cabal
rio/src/RIO.hs
rio/src/RIO/Lens.hs
rio/src/RIO/Prelude/Lens.hs

These extended exports should be enough to ensure that most users won't need to depend on `microlens` independently.
Note that I've removed the custom reimplementation of `view`, and instead pulled it from `microlens-mtl`, the transitive deps of which were already in `rio`.

Expanding Microlens

---

rio/ChangeLog.md
rio/package.yaml
rio/rio.cabal
rio/src/RIO/Prelude.hs
rio/src/RIO/Prelude/Types.hs

This PR exposes `Bifunctor`, `Bifoldable`, and `Bitraversable`, which are in `base` as of `4.10`. Luckily, `rio` already enforces a `>= 4.10` bound!
**Note:** The `first` and `second` functions from `Control.Arrow`, while the originals, can be considered special cases of those from `Bifunctor`. Specially, the `Bifunctor` variants work on both Tuple and `Either`, while those of Arrow work only on Tuple. So, this PR hides the Arrow variants. 
Functions which have *not* been exposed:
- `biforM`
- `bimapM`
- `bisequenceA`
- `bimapM_`
- `biforM_`
- `bimsum`
- `bisequenceA_`
- `bimapDefault`
- `bifoldMapDefault`

Bi* Classes

---

rio/src/RIO/Prelude/Logger.hs
rio/src/RIO/Process.hs

The motivation for this pull request is that the exisitng hard-coded colours in `RIO.Process.withProcessTimeLog` and `RIO.Prelude.Logger.simpleLogFunc` (for timestamps and locs) are not visible when using the Solarised Dark theme.
Tested on Windows 10 by sucessfully rebuilding `stack` (which depends on `rio`), with and without making use of the option to customise logger colours.
The defaults are the same as what was previously hard-coded and `RIO.Prelude.Logger` does not export the constructor of `LogOption`, so existing code depending on `rio` should not be affected.
A new `LogColors` type is exported, and an associated accessor (`logFuncColorsL`):
```haskell
data LogColors = LogColors
{ -- | The color associated with each 'LogLevel'.
logColorLogLevels :: !(LogLevel -> Utf8Builder)
-- | …
```

Add colours to the `LogOption` constructor

---

rio-orphans/README.md

See the `rio-orphans` `ChangeLog.md` for v0.1.1.0 changes.
Also lists the items by alphabetical order.

Update rio-orphans README.md for v0.1.1.0

---

rio/ChangeLog.md
rio/src/RIO/Prelude.hs

These guys have been available since base-4.10 which is already the lower bound for rio.

Expose `fromLeft` and `fromRight` from `RIO.Prelude`

---

stack.yaml

`stack --nix build` should just work now.

enabling simpler build for nix via stack

---

rio-orphans/ChangeLog.md
rio-orphans/package.yaml
rio-orphans/rio-orphans.cabal
rio-orphans/src/RIO/Orphans.hs

This is needed due to [persist-sqlite](https://github.com/yesodweb/persistent/blob/master/persistent-sqlite/Database/Persist/Sqlite.hs#L142) adding a `MonadLoggerIO` constraint to various functions.
I found this bug due to a call to `withSqliteConnInfo` in [pantry](https://github.com/commercialhaskell/pantry/blob/master/src/Pantry/SQLite.hs#L41).

Add MonadLoggerIO instance for RIO

---

rio/ChangeLog.md
rio/package.yaml
rio/src/RIO/Process.hs
rio/test/RIO/Prelude/ExtraSpec.hs

On windows, env vars are generally case-insensitive.
Due to 'type EnvVars = Map Text Text' augmentPathMap
assumes full uppercase "PATH" variable, which may lead
to surprising behavior if the current map
has a variable such as "Path".
This patch folds over the map and inserts any path
key as "PATH" on windows. That also means: if there
are multiple, the "last" one wins. There generally
isn't a sane solution if the input map already
has multiple path keys (how should they be merged,
which order?).
Fixes #234

Fix augment path

---

rio/src/RIO/Prelude/RIO.hs

Use identity lens for these Has instances instead of recreating it.

Use identity lens

---

rio/package.yaml

`Lens.Micro.singular` is not available before `microlens-0.4.2.0`.

Require microlens >= 0.4.2.0

---

rio/src/RIO/Map.hs
stack.yaml

`containers-0.8` is a boot package of GHC 9.14.1-alpha1, and removes `Data.Map.Strict.showTree` and `Data.Map.Strict.showTreeWith` first deprecated in `containers-0.5.9.1`.
Also bumps `stack.yaml` to Stackage LTS Haskell 24.6.

Support GHC 9.14.1-alpha1 and `containers-0.8`
